wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.0
    framework: huggingface
    huggingface_version: 4.35.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1700826760.245572
    t:
      1:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 98
      - 105
      2:
      - 1
      - 11
      - 49
      - 51
      - 55
      - 71
      - 84
      - 98
      - 105
      3:
      - 2
      - 23
      4: 3.8.10
      5: 0.16.0
      6: 4.35.2
      8:
      - 1
      - 5
      13: linux-x86_64
